//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralNotes.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMensages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMensages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneralNotes.Exceptions.ResourceErrorMensages", typeof(ResourceErrorMensages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A altura do aluno deve ser informada..
        /// </summary>
        public static string ALTURA_STUDENT_EMBRANCO {
            get {
                return ResourceManager.GetString("ALTURA_STUDENT_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &quot;Contato&quot; deve conter apenas números e os caracteres especiais (), -. Remova caracteres inválidos..
        /// </summary>
        public static string CARACTERES_TELEFONE_INVALIDOS {
            get {
                return ResourceManager.GetString("CARACTERES_TELEFONE_INVALIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &quot;Contato&quot; deve conter apenas números e os caracteres especiais (), -. Remova caracteres inválidos..
        /// </summary>
        public static string CARACTERES_TELEFONE_INVALIDOS1 {
            get {
                return ResourceManager.GetString("CARACTERES_TELEFONE_INVALIDOS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, descreva alguns detalhes sobre o exercício..
        /// </summary>
        public static string DETALHE_EXERCÍCIO_EMBRANCO {
            get {
                return ResourceManager.GetString("DETALHE_EXERCÍCIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &quot;Contato&quot; deve ter pelo menos 10 dígitos (incluindo o DDD). Forneça um número de telefone mais detalhado..
        /// </summary>
        public static string DÍGITOS_TELEFONE_INSUFICIENTES {
            get {
                return ResourceManager.GetString("DÍGITOS_TELEFONE_INSUFICIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &quot;Contato&quot; deve ter pelo menos 10 dígitos (incluindo o DDD). Forneça um número de telefone mais detalhado..
        /// </summary>
        public static string DÍGITOS_TELEFONE_INSUFICIENTES1 {
            get {
                return ResourceManager.GetString("DÍGITOS_TELEFONE_INSUFICIENTES1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail informado já esta registrado na base de dados..
        /// </summary>
        public static string EMAIL_JA_REGISTRADO {
            get {
                return ResourceManager.GetString("EMAIL_JA_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail informado já esta registrado na base de dados..
        /// </summary>
        public static string EMAIL_JA_REGISTRADO1 {
            get {
                return ResourceManager.GetString("EMAIL_JA_REGISTRADO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail do usuário deve ser informado..
        /// </summary>
        public static string EMAIL_STUDENT_EMBRANCO {
            get {
                return ResourceManager.GetString("EMAIL_STUDENT_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail do usuário é inválido..
        /// </summary>
        public static string EMAIL_STUDENT_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_STUDENT_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O email deve ser um endereço válido e conter apenas caracteres permitidos. Ele deve seguir o formato nome@dominio.com.
        /// </summary>
        public static string EMAIL_USUARIO_CARACTERES_INVALIDOS {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_CARACTERES_INVALIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail do usuário deve ser informado..
        /// </summary>
        public static string EMAIL_USUARIO_EMBRANCO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail do usuário é inválido..
        /// </summary>
        public static string EMAIL_USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, informe o equipamento que será utilizado o exercício..
        /// </summary>
        public static string EQUIPAMENTO_EXERCÍCIO_EMBRANCO {
            get {
                return ResourceManager.GetString("EQUIPAMENTO_EXERCÍCIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, insira exercícios em sua rotina..
        /// </summary>
        public static string EXERCÍCIOS_EMBRANCO {
            get {
                return ResourceManager.GetString("EXERCÍCIOS_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a campo &quot;Contato&quot; deve ter o formato (99) 9999-9999. Certifique-se de seguir o formato padrão..
        /// </summary>
        public static string FORMATO_TELEFONE_INVALIDO {
            get {
                return ResourceManager.GetString("FORMATO_TELEFONE_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a campo &quot;Contato&quot; deve ter o formato 99 9999-9999. Certifique-se de seguir o formato padrão..
        /// </summary>
        public static string FORMATO_TELEFONE_INVALIDO1 {
            get {
                return ResourceManager.GetString("FORMATO_TELEFONE_INVALIDO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O histórico médico do aluno deve ser informado..
        /// </summary>
        public static string HISTORICO_MEDICO_EMBRANCO {
            get {
                return ResourceManager.GetString("HISTORICO_MEDICO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A idade do estudante deve ser informada..
        /// </summary>
        public static string IDADE_STUDENT_EMBRANCO {
            get {
                return ResourceManager.GetString("IDADE_STUDENT_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail e/ou senha estão incorretos..
        /// </summary>
        public static string LOGIN_INVALIDO {
            get {
                return ResourceManager.GetString("LOGIN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, informe o nome do exercício..
        /// </summary>
        public static string NOME_EXERCÍCIO_EMBRANCO {
            get {
                return ResourceManager.GetString("NOME_EXERCÍCIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe o nome da sua rotina de exercícios..
        /// </summary>
        public static string NOME_ROTINA_EMBRANCO {
            get {
                return ResourceManager.GetString("NOME_ROTINA_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do usuário deve ser informado..
        /// </summary>
        public static string NOME_STUDENT_EMBRANCO {
            get {
                return ResourceManager.GetString("NOME_STUDENT_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do usuário deve ser informado..
        /// </summary>
        public static string NOME_USUARIO_EMBRANCO {
            get {
                return ResourceManager.GetString("NOME_USUARIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, informe o carga a ser utilizada no exercício..
        /// </summary>
        public static string PESO_EXERCÍCIO_EMBRANCO {
            get {
                return ResourceManager.GetString("PESO_EXERCÍCIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O peso do aluno deve ser informado..
        /// </summary>
        public static string PESO_STUDENT_EMBRANCO {
            get {
                return ResourceManager.GetString("PESO_STUDENT_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, informe a quantidade de repetições do exercício..
        /// </summary>
        public static string REPERTICOES_EXERCÍCIO_EMBRANCO {
            get {
                return ResourceManager.GetString("REPERTICOES_EXERCÍCIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma rotina encontrada..
        /// </summary>
        public static string ROTINA_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("ROTINA_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha atual é inválida..
        /// </summary>
        public static string SENHA_ATUAL_INVALIDA {
            get {
                return ResourceManager.GetString("SENHA_ATUAL_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve ter pelo menos 8 caracteres e incluir pelo menos uma letra maiúscula, uma letra minúscula, um número e um caractere especial (como @, $, !, %, *, ?, &amp;).
        /// </summary>
        public static string SENHA_USUARIO_CARACTERES_INVALIDOS {
            get {
                return ResourceManager.GetString("SENHA_USUARIO_CARACTERES_INVALIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha do usuário deve ser informada..
        /// </summary>
        public static string SENHA_USUARIO_EMBRANCO {
            get {
                return ResourceManager.GetString("SENHA_USUARIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter no minimo 8 caracteres..
        /// </summary>
        public static string SENHA_USUARIO_MINIMO_OITO_CARACTERES {
            get {
                return ResourceManager.GetString("SENHA_USUARIO_MINIMO_OITO_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Estudante informado não pode ser encontrado. Verifique se ele é existe ou é valido..
        /// </summary>
        public static string STUDANTE_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("STUDANTE_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe seu tempo de descanso..
        /// </summary>
        public static string TEMPO_ESPERA_EMBRANCO {
            get {
                return ResourceManager.GetString("TEMPO_ESPERA_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, informe o tipo do exercício..
        /// </summary>
        public static string TIPO_EXERCÍCIO_EMBRANCO {
            get {
                return ResourceManager.GetString("TIPO_EXERCÍCIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado..
        /// </summary>
        public static string USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não tem permissão para acessar este recurso..
        /// </summary>
        public static string USUARIO_SEM_PERMISSAO {
            get {
                return ResourceManager.GetString("USUARIO_SEM_PERMISSAO", resourceCulture);
            }
        }
    }
}
